// Generates generated/payloads.generated.ts — one TypeScript interface per event payload
// ($def) across every schema, plus the EventEnvelope. Common refs (Money, etc.) are emitted
// once and de-duplicated. The curated generated/events.ts re-exports these and adds the
// typed EventPayloadMap. Usage: npm run generate:ts
import { compile } from "json-schema-to-typescript";
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const schemasDir = join(root, "schemas");
const outFile = join(root, "generated", "payloads.generated.ts");

const SKIP_FILE = new Set(["common.schema.json"]);
const opts = { bannerComment: "", additionalProperties: false, cwd: schemasDir, declareExternallyReferenced: true };

const banner = `/* AUTO-GENERATED by scripts/generate-types.mjs — DO NOT EDIT.
 * One interface per event payload, generated from schemas/*.json.
 * Regenerate: npm run generate:ts
 */\n\n`;

const chunks = [];

// envelope (whole-file)
{
  const doc = JSON.parse(await readFile(join(schemasDir, "envelope.schema.json"), "utf8"));
  chunks.push(await compile(doc, "EventEnvelope", opts));
}

// each context: compile every $def individually so payload interfaces are emitted
const files = (await readdir(schemasDir)).filter((f) => f.endsWith(".schema.json") && !SKIP_FILE.has(f) && f !== "envelope.schema.json").sort();
for (const file of files) {
  const doc = JSON.parse(await readFile(join(schemasDir, file), "utf8"));
  for (const [name, def] of Object.entries(doc.$defs ?? {})) {
    if (def.type !== "object") continue; // skip doc-only / non-object defs
    const sub = { $schema: doc.$schema, $id: `${doc.$id}#/$defs/${name}`, title: def.title ?? name, ...def };
    chunks.push(await compile(sub, def.title ?? name, opts));
  }
}

// de-duplicate top-level declarations by name (common types repeat across payloads)
const seen = new Set();
const declRe = /export (?:interface|type) (\w+)/;
const out = [banner];
for (const chunk of chunks) {
  // split into top-level declaration blocks separated by blank lines
  const blocks = chunk.split(/\n(?=export )/);
  for (const block of blocks) {
    const m = block.match(declRe);
    if (!m) { if (block.trim()) out.push(block.trim() + "\n"); continue; }
    if (seen.has(m[1])) continue;
    seen.add(m[1]);
    out.push(block.trim() + "\n");
  }
}

await mkdir(dirname(outFile), { recursive: true });
await writeFile(outFile, out.join("\n"), "utf8");
console.log(`Wrote ${outFile} (${seen.size} types)`);
